language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-text
